# Generated by Django 5.0 on 2025-01-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='width',
        ),
    ]
