# Generated by Django 5.0 on 2025-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_imagefile_channels_remove_imagefile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
